package com.coursemanager.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;
import tk.mybatis.mapper.annotation.ColumnType;

/**
 * 描述:  notice_info 对应的model类.<br>
 * WARNING不是表中的字段必须加@Transient字段
 * @author framework generator
 * @date 2019年03月09日
 */
@Table(name = "notice_info")
public class NoticeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.id
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.user_id
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.title
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.message
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.url
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.send_user
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    private String sendUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.insert_time
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.read_status
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    private Integer readStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.use_status
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    private Integer useStatus;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.id
     *
     * @return the value of notice_info.id
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.id
     *
     * @param id the value for notice_info.id
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.user_id
     *
     * @return the value of notice_info.user_id
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.user_id
     *
     * @param userId the value for notice_info.user_id
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.title
     *
     * @return the value of notice_info.title
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.title
     *
     * @param title the value for notice_info.title
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.message
     *
     * @return the value of notice_info.message
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.message
     *
     * @param message the value for notice_info.message
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.url
     *
     * @return the value of notice_info.url
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.url
     *
     * @param url the value for notice_info.url
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.send_user
     *
     * @return the value of notice_info.send_user
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public String getSendUser() {
        return sendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.send_user
     *
     * @param sendUser the value for notice_info.send_user
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public void setSendUser(String sendUser) {
        this.sendUser = sendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.insert_time
     *
     * @return the value of notice_info.insert_time
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.insert_time
     *
     * @param insertTime the value for notice_info.insert_time
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.read_status
     *
     * @return the value of notice_info.read_status
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public Integer getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.read_status
     *
     * @param readStatus the value for notice_info.read_status
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public void setReadStatus(Integer readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.use_status
     *
     * @return the value of notice_info.use_status
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.use_status
     *
     * @param useStatus the value for notice_info.use_status
     *
     * @mbg.generated Sat Mar 09 12:34:14 CST 2019
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }
}